#+title: ox-deck.el
#+author: Naoya Yamashita

[[https://github.com/conao3/ox-deck.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/ox-deck.el.svg?style=flat-square]]
[[https://github.com/conao3/ox-deck.el/releases][https://img.shields.io/github/tag/conao3/ox-deck.el.svg?style=flat-square]]
[[https://github.com/conao3/ox-deck.el/actions][https://github.com/conao3/ox-deck.el/workflows/Main%20workflow/badge.svg]]

An Org-mode export backend for [[https://github.com/k1LoW/deck][Deck]], the Markdown-based presentation tool.

* Overview

ox-deck.el provides a custom Org export backend that converts your Org documents into Deck-flavored Markdown. This allows you to write presentations in Org-mode and export them directly to a format that Deck can render as beautiful slide decks.

[[https://github.com/conao3/ox-deck.el][https://raw.githubusercontent.com/conao3/files/master/blob/ox-deck.el/ox-deck.gif]]

* Features

- Seamless integration with Org's export dispatcher
- First-level headlines become slide separators
- Full support for GitHub Flavored Markdown via ox-gfm
- Export to buffer, file, or file with auto-open

* Requirements

- Emacs 30.1 or later
- Org-mode 9.0 or later
- [[https://github.com/larstvei/ox-gfm][ox-gfm]]

* Installation

** Using leaf.el

#+begin_src emacs-lisp
(leaf ox-deck
  :vc (:url "https://github.com/conao3/ox-deck.el.git")
  :ensure t
  :after org
  :require t)
#+end_src

** Using use-package with vc

#+begin_src emacs-lisp
(use-package ox-deck
  :vc (:url "https://github.com/conao3/ox-deck.el.git")
  :after org)
#+end_src

** Manual Installation

Clone the repository and add it to your load path:

#+begin_src shell
git clone https://github.com/conao3/ox-deck.el.git ~/.emacs.d/site-lisp/ox-deck
#+end_src

#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/site-lisp/ox-deck")
(require 'ox-deck)
#+end_src

* Usage

Once installed, ox-deck integrates with Org's export dispatcher. Press =C-c C-e= in any Org buffer to open the export menu, then select:

- =d D= - Export to a temporary buffer
- =d d= - Export to a Markdown file
- =d o= - Export to a file and open it

The exporter converts first-level Org headlines into Deck slide separators (=---=), making it easy to structure your presentation.

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests on GitHub.

** Development Setup

Install [[https://github.com/conao3/keg][keg]] for running tests:

#+begin_src shell
git clone https://github.com/conao3/keg ~/.keg
export PATH="$HOME/.keg/bin:$PATH"
#+end_src

** Testing

#+begin_src shell
make test
#+end_src

* License

GPL-3.0. See [[https://github.com/conao3/ox-deck.el/blob/master/LICENSE][LICENSE]] for details.

Copyright (c) Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][@conao3]])
